"""Alembic environment for the async (asyncpg) engine.

The database URL is **not** stored in alembic.ini. It comes from the same
`Settings` object the application uses, so there is one source of truth and no
password sitting in a tracked file. `ALEMBIC_DATABASE_URL` overrides it, which
is what lets a baseline revision be autogenerated against a throwaway database
without touching the real one.

Importing `app.models` is what populates `Base.metadata` — without it every
table looks missing and autogenerate would propose dropping the schema.
"""

from __future__ import annotations

import asyncio
import os
from logging.config import fileConfig

from sqlalchemy import pool
from sqlalchemy.engine import Connection
from sqlalchemy.ext.asyncio import create_async_engine

from alembic import context

from app.core.config import settings
from app.core.database import Base
from app import models  # noqa: F401  (registers every mapper on Base.metadata)

config = context.config

if config.config_file_name is not None:
    fileConfig(config.config_file_name)

target_metadata = Base.metadata


def get_url() -> str:
    return os.getenv("ALEMBIC_DATABASE_URL") or settings.database_url


def _configure(**kwargs) -> None:
    context.configure(
        target_metadata=target_metadata,
        # Postgres enums, server defaults and varchar lengths all drift silently
        # otherwise — the exact class of change that made migrate.py necessary.
        compare_type=True,
        compare_server_default=True,
        **kwargs,
    )


def run_migrations_offline() -> None:
    """Emit SQL to stdout instead of running it (`alembic upgrade --sql`)."""
    _configure(
        url=get_url(),
        literal_binds=True,
        dialect_opts={"paramstyle": "named"},
    )
    with context.begin_transaction():
        context.run_migrations()


def do_run_migrations(connection: Connection) -> None:
    _configure(connection=connection)
    with context.begin_transaction():
        context.run_migrations()


async def run_async_migrations() -> None:
    connectable = create_async_engine(get_url(), poolclass=pool.NullPool)
    async with connectable.connect() as connection:
        await connection.run_sync(do_run_migrations)
    await connectable.dispose()


def run_migrations_online() -> None:
    asyncio.run(run_async_migrations())


if context.is_offline_mode():
    run_migrations_offline()
else:
    run_migrations_online()
